version: 2

defaults: &defaults
  working_directory: ~/demoscene-toolchain
  docker:
    - image: cahirwpz/demoscene-toolchain:latest

jobs:
  m68k:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - m68k-cache-{{ .Branch }}-{{ checksum ".circleci/DATESTAMP" }}
      - run: './toolchain-m68k --quiet download'
      - save_cache:
          key: m68k-cache-{{ .Branch }}-{{ checksum ".circleci/DATESTAMP" }}
          paths:
            - .build-m68k
      - run: './toolchain-m68k --quiet build --prefix=/usr/local'
      - run: 'tar cvzf /demoscene-toolchain.tar.gz /usr/local'
      - store_artifacts:
          path: /demoscene-toolchain.tar.gz

workflows:
  version: 2
  demoscene-toolchain:
    jobs:
      - m68k
