version: 2

defaults: &defaults
  working_directory: ~/demoscene-toolchain
  docker:
    - image: cahirwpz/amigaos-cross-toolchain-buildenv:latest

jobs:
  m68k:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - m68k-cache-{{ .Branch }}-{{ checksum ".circleci/DATESTAMP" }}
      - run: './toolchain-m68k --quiet download'
      - save_cache:
          key: m68k-cache-{{ .Branch }}-{{ checksum ".circleci/DATESTAMP" }}
          paths:
            - .build-m68k
      - run: './toolchain-m68k --quiet build'
      - save_cache:
          key: m68k-amigaos-{{ .Branch }}-{{ .Revision }}
          paths: m68k-amigaos

workflows:
  version: 2
  demoscene-toolchain:
    jobs:
      - m68k
