name: Demoscene Toolchain

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cahirwpz/demoscene-toolchain:latest

    steps:
    - uses: actions/checkout@v2

    - name: Download toolchain
      run: ./toolchain-m68k --quiet download

    - name: Cache external archives
      uses: actions/cache@v2
      env:
        cache-name: cache-externals
      with:
        path: |
          - .build-m68k/archives
          - submodules/binutils-gdb
          - submodules/fd2pragma
          - submodules/fd2sfd
          - submodules/fs-uae
          - submodules/gcc-2.95.3
          - submodules/python-amidev
          - submodules/python-lhafile
          - submodules/sfdc
        key: 20220418-1

    - name: Build toolchain
      run: ./toolchain-m68k --quiet build --prefix=/usr/local

    - name: Archive toolchain
      run: tar cvzf demoscene-toolchain.tar.gz /usr/local

    - name: Upload toolchain
      uses: actions/upload-artifact@v2
      with:
        name: demoscene-toolchain
        path: demoscene-toolchain.tar.gz
